### ISSUE TITLE
don't works in 3126

### ISSUE THREAD

**Issue by ildarkhasanshin** [gtarawneh/languagetool-sublime#14]
```
File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
return self.run(edit)
File "LanguageTool in /home/ildar/.config/sublime-text-3/Installed Packages/LanguageTool.sublime-package", line 237, in run
File "LTServer in /home/ildar/.config/sublime-text-3/Installed Packages/LanguageTool.sublime-package", line 10, in getResponse
File "LTServer in /home/ildar/.config/sublime-text-3/Installed Packages/LanguageTool.sublime-package", line 26, in _post
File "LTServer in /home/ildar/.config/sublime-text-3/Installed Packages/LanguageTool.sublime-package", line 38, in _post_ST3
AttributeError: 'module' object has no attribute 'parse'
```

st 3126
ubuntu 16.04 x64

**Comment by gtarawneh** [comment]
Can you please test again on the current version? Please uninstall and re-install by selecting `Package Control: Add Repository` from the command palette then pasting `https://github.com/gtarawneh/languagetool-sublime`. This will install the latest version from GitHub as it's yet released on package control. Thanks.

**Comment by ildarkhasanshin** [comment]
now
`Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "LanguageTool in /home/ildar/.config/sublime-text-3/Installed Packages/languagetool-sublime.sublime-package", line 237, in run
  File "LTServer in /home/ildar/.config/sublime-text-3/Installed Packages/languagetool-sublime.sublime-package", line 15, in getResponse
  File "LTServer in /home/ildar/.config/sublime-text-3/Installed Packages/languagetool-sublime.sublime-package", line 31, in _post
  File "LTServer in /home/ildar/.config/sublime-text-3/Installed Packages/languagetool-sublime.sublime-package", line 43, in _post_ST3
AttributeError: 'module' object has no attribute 'parse'`

**Comment by Kristinita** [comment]
@ildarkhasanshin, 

[Offtop]. Макрос для быстрой подсветки Traceback, дабы разработчикам, рассматривающим issue, было удобно разбираться.

**Код**: <https://dpaste.de/xPaF>
**Демонстрация**: <http://i.imgur.com/OtZUpVn.gif>

Спасибо.
